name: build_test_deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo on machine
      uses: actions/checkout@v4 

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm install
      working-directory: client 

    - name: Start server
      run: node server.js &
      working-directory: server  

    - name: Set BE URL for local tests    
      run: echo "export const settings = {host:\"http://localhost:8080\"}" > src/config.js
      working-directory: client

    - name: Start Front End
      run: npm start &
      working-directory: client  

    - name: Wait for servers to initialize
      run: sleep 5

    - name: Run tests
      run: npm run test

  deploy_server_to_prod:
      runs-on: ubuntu-latest
      needs: build_test

      steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVER_DEPLOY_HOOK }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true 
    
  deploy_client_to_prod:
      runs-on: ubuntu-latest
      needs: build_test

      steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_CLIENT_DEPLOY_HOOK }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true 
