# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build_test_deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Navigate to client folder
      run: cd client
    - name: Install packages
      run: npm install
    - name: Navigate to server folder
      run: cd .. 
    - name: Start server
      run: node server.js &
    - name: Navigate to client again 
      run: cd .. 
    - run: cd client 
    - name: Run tests 
      run: npm start & 
    - run: npm run tests