name: build_test_deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
#  build_test:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout repo on machine
#      uses: actions/checkout@v4 
#
#    - name: Use Node.js 20.x
#      uses: actions/setup-node@v4
#      with:
#        node-version: 20.x
#        cache: 'npm'
#        cache-dependency-path: package-lock.json
#
#    - name: Install dependencies
#      run: npm install  # Since package.json is at root, install from root
#
#    - name: Start server
#      run: node server/server.js &  # Assuming server.js is inside the "server" folder
#
#    - name: Start HTTP server
#      run: npm start &  # Starts the frontend server
#
#    - name: Wait for servers to start
#      run: sleep 5  # Gives servers time to initialize
#
#    - name: Run tests
#      run: npm run test 
    deploy_server_to_prod:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVER_DEPLOY_HOOK }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true 
    
    deploy_client_to_prod:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_CLIENT_DEPLOY_HOOK }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true 
