name: build_test_deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo on machine
      uses: actions/checkout@v4 

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Install packages
      run: npm install
      working-directory: client

    - name: Start server
      run: node server.js &
      working-directory: server  # Assuming the server is in the "server" directory

    - name: Run tests 
      run: |
        npm start &
        sleep 5  # Wait for the server to start
        npm run test
      working-directory: client